# Generated by Django 3.1.6 on 2021-03-12 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200407_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_delivery',
            field=models.BooleanField(default=False, help_text='Доставка или самовывоз'),
        ),
    ]
